export declare function fillRepeating(dstBuffer: number[] | Int8Array | Int16Array | Int32Array | Uint8ClampedArray | Uint32Array | Uint32Array | Uint32Array | Float32Array | Float64Array | BigUint64Array | BigInt64Array, start: number, end: number): void;
export declare function fillRepeatingInt8(dstBuffer: Int8Array, start: number, end: number): void;
export declare function fillRepeatingInt16(dstBuffer: Int16Array, start: number, end: number): void;
export declare function fillRepeatingInt32(dstBuffer: Int32Array, start: number, end: number): void;
export declare function fillRepeatingUint8Clamped(dstBuffer: Uint8ClampedArray, start: number, end: number): void;
export declare function fillRepeatingUInt8(dstBuffer: Uint32Array, start: number, end: number): void;
export declare function fillRepeatingUInt16(dstBuffer: Uint32Array, start: number, end: number): void;
export declare function fillRepeatingUInt32(dstBuffer: Uint32Array, start: number, end: number): void;
export declare function fillRepeatingFloat32(dstBuffer: Float32Array, start: number, end: number): void;
export declare function fillRepeatingFloat64(dstBuffer: Float64Array, start: number, end: number): void;
export declare function fillRepeatingBigUint64(dstBuffer: BigUint64Array, start: number, end: number): void;
export declare function fillRepeatingBigInt64(dstBuffer: BigInt64Array, start: number, end: number): void;
